### ISSUE TITLE
Feature request: annotations & two-way sync

### ISSUE THREAD

**Issue by StianOby** [mickstar/Zoo-For-Zotero#10]
As a long term goal, I suggest that the app should support two-way synchronization, including annotations. This could be done in two ways:

(1) As a pure two-way file sync, with the annotations done by another app (a good PDF reader for Android that works well with Zoo).
(2) With the PDF reader and annotator integrated into Zoo.

The latter option would probably reduce the risk of complications arising from moving between applications. But I guess it would be quite an effort to "reinvent the wheel" by developing a PDF reader/annotator only for use within Zoo. Though it may perhaps be possible to integrate code from GPL-licensed PDF readers already on the market: https://github.com/offa/android-foss#-document--pdf-viewer For example the MuPDF library: https://mupdf.com/

**Comment by mickstar** [comment]
Resolved in #45
