### ISSUE TITLE
[Bug] Deleted collections still displaying

### ISSUE THREAD

**Issue by sjsunderland** [mickstar/Zoo-For-Zotero#101]
Hi,
First a heartfelt thank you, the app is very, very useful in my everyday.
I'm experiencing a display bug whilst using the app. It displays collections that I have deleted from my Zotero library. These do not appear on the desktop app on my macbook, but still display in the Zoo for Zotero app. See screenshots:

On my desktop app on my macbook, the collection displays the following sub-collections:
<img width="186" alt="Capture d’écran 2020-09-16 à 12 54 44" src="https://user-images.githubusercontent.com/65330133/93328642-480ff700-f81c-11ea-880f-bd0eb2ad9183.png">

Whilst on my Zoo for Zotero app, it displays the following:
![Screenshot_20200916-125259](https://user-images.githubusercontent.com/65330133/93329014-d8e6d280-f81c-11ea-8dc4-51db769fe2c1.png)

I tried re-starting the app and the tablet on which I use it, as well as uninstalling and re-installing, but no success Is there something I could do here?

**Comment by mickstar** [comment]
yeah the app cannot sync delete operations yet.

**Comment by sjsunderland** [comment]
Alright, thanks for the quick response.

**Comment by arcturus140** [comment]
> yeah the app cannot sync delete operations yet.

then it's a feature request, not a bug.

**Comment by mickstar** [comment]
collections should delete as of 2.8
