### ISSUE TITLE
Feature request: access attached pdfs more easily

### ISSUE THREAD

**Issue by celmi** [mickstar/Zoo-For-Zotero#103]
I'm finding it a bit cumbersome to have to open an Zotero-entry, scroll down through all fields, to retrieve an attached pdf at the very bottom. My usual workflow is to just get right to the pdf as quick as possible.

Suggestions: theres lots of free space in the library view, why not a second column displaying attached pdf-files? Or offer me the pdf-attachments at the top of an entry, instead of at the bottom?

thanks!

**Comment by mickstar** [comment]
Yes I agree, unfortunately when I tried to add a pdf icon to the list view I found it required quite a bit of effort as it requires a library change.

Regarding putting the attachment section at the top, although much more convenient, design wise it seems odd to have attachments at the top.

As a compromise I suggest using this option
![Screenshot_20200917-213306_Zoo for Zotero.jpg](https://user-images.githubusercontent.com/89431/93465517-43d3fe80-f92e-11ea-9ceb-c131d02c33c6.jpg)

The best solution is the pdf icon in the list view but I doubt I will ever find the time.
