### ISSUE TITLE
pdf change detection and upload issue with acrobat reader

### ISSUE THREAD

**Issue by fkgruber** [mickstar/Zoo-For-Zotero#108]
Hi,
I'm running into an issue when I modify the pdf with Acrobat reader. When I go back to zoo it does not detect the changes in the pdf. Forcing reupload sends error.

I tried on a galaxy note 10.  Pdf change detection and reupload works fine with other readers like xodo.

Acrobat has the advantage that it has a better pdf reflow feature.

There seems to be a bug here.

**Comment by mickstar** [comment]
Yes, this is an issue with Acrobat, they write the changes to a copy of the file thats stored in the app's directory.
There isn't actually a way for Zoo to detect the changes as the original file doesn't change. You will have to use pdf editors like Xodo.
