### ISSUE TITLE
Feature request: complete sync

### ISSUE THREAD

**Issue by StianOby** [mickstar/Zoo-For-Zotero#11]
It should be possible to always have our entire library of files synced to our device, if one so prefers. That way files would be accessible even if you are offline, and in any even without having to wait for files to be downloaded.

This should probably not be the default setting, though.

**Comment by greatleapingcrab** [comment]
Sad to see the wontfix label on this :(

**Comment by mickstar** [comment]
I have found android's framework for storage and SD card access as being rather rigid and not particularly pleasant. I could implement the feature but it's low on my priority list

**Comment by mickstar** [comment]
in #35 i rewrote the storage code and this is now quite possible to do. I will implement it soon.

**Comment by mickstar** [comment]
added feature in #45 
expect it in the playstore by the end of the week
