### ISSUE TITLE
[Feature Request] share items

### ISSUE THREAD

**Issue by arcturus140** [mickstar/Zoo-For-Zotero#114]
I would like to share items, like web links or hosted documents, with other accounts, such as Whatsapp or Email, using Android share function.

**Comment by mickstar** [comment]
Good idea,
I will add it for the next version.

**Comment by mickstar** [comment]
What should the format of the text be?
[Title] - [Author] - [Date] ?

**Comment by arcturus140** [comment]
I am using author - year - title, this is default setting in Zotero

**Comment by arcturus140** [comment]
thank you for implementing this, it works great
