### ISSUE TITLE
Feature request: Some indication an item contains an attached pdf

### ISSUE THREAD

**Issue by jacobrosenthal** [mickstar/Zoo-For-Zotero#119]
I have a large list of items syncing to my ereader, but only some have pdf attached.

Thanks for a great app. Works great even on a tablet

Edit: Ah I found the filter. It would still be nice to have an indicator.

**Comment by mickstar** [comment]
It's a good idea it just requires a fair bit of work on my end, I need to completely change the listview

**Comment by mickstar** [comment]
resolved in #135
