### ISSUE TITLE
Feature request: show 'My Publications' in collections

### ISSUE THREAD

**Issue by jorjio** [mickstar/Zoo-For-Zotero#120]
Hi,
Showing the 'My Publications' collection will be helpful.
Thank you for an amazing app!

**Comment by mickstar** [comment]
Sure, I will include it in the next version.

**Comment by jorjio** [comment]
Thanks so much!

**Comment by mickstar** [comment]
added here fcb205414a0186309a8736f56032fdead2ecf012
