### ISSUE TITLE
Re-uploading to WebDAV fails

### ISSUE THREAD

**Issue by tuetschek** [mickstar/Zoo-For-Zotero#128]
Whenever I try to reupload an annotated PDF to WebDAV, I get a SardineException saying "Error contacting `https://<my WebDAV>/zotero/<ID string>.prop` (404 Not Found)". When I look at the server, I can see that that file really isn't there, but I can see a file called `<ID string>_NEW.prop`. Downloading from WebDAV works fine. I'm getting the same problem on 2 different devices. Sometimes the error is a 400 Bad Request instead.  Am I doing something wrong?

**Comment by mickstar** [comment]
The app uploads x_NEW.zip, deletes the original x.prop and then renames
x_new to X.prop

It would seem the rename is failing. Some WebDAV servers dont seem to
handle the rename request properly.

Which WebDAV provider are you using?

**Comment by tuetschek** [comment]
Hmm, that sounds like that may be the problem. I'm running my own WebDAV on a Raspberry PI, using lighttpd (version 1.4.53).

**Comment by tuetschek** [comment]
Looks like it might be related to this: https://redmine.lighttpd.net/issues/2979 . Unfortunately there's no easy way for me to install a newer version of lighttpd (short of changing the distribution or compiling from scratch), so I'll have to live with it.

**Comment by gstrauss** [comment]
You might be able to work around the issue in https://redmine.lighttpd.net/issues/2979 by configuring webdav in the top-level (global scope) of lighttpd.conf.  However, based on your description above, it does not sound like that is your issue, as you are running lighttpd 1.4.53, not lighttpd 1.4.54.

**Comment by tuetschek** [comment]
Yeah, unfortunately Raspbian doesn't have anything newer at the moment 🤨. Thanks for the hint though – once I find the way to upgrade, I'll need to check the configuration.

**Comment by fiqas** [comment]
I have the same issue with 4shared as my WebDAV. Any ideas?

**Comment by gstrauss** [comment]
Raspian is based on Debian.  The latest lighttpd release (lighttpd-1.4.59) is available in buster-backports.

https://github.com/superjamie/lazyweb/wiki/Raspberry-Pi-Debian-Backports
`sudo apt-get -t buster-backports install lighttpd`

**Comment by davidenitti** [comment]
I get the same error. did you find a solution?
