### ISSUE TITLE
Server Response: 412 null

### ISSUE THREAD

**Issue by raffaem** [mickstar/Zoo-For-Zotero#140]
I am using Zoo for Zotero and annotate the PDF on my tablet.

Then I close the PDF annotator application and Zoo for Zotero asks me if I want to upload the PDF.

I click Yes then it shows the error "Server Repsonse: 412 null"

I am positive the internet connection on the tablet works

**Comment by raffaem** [comment]
Now it gives me "java.lang.RuntimeException: java.net.SocketTimeoutException: timeout"

**Comment by raffaem** [comment]
I believe it's the corporate firewall I am behind ... which protocol and port does Zoo for Zotero uses?

**Comment by mickstar** [comment]
Is this for WebDAV or zotero API?

If it's the zotero API you can see here what the codes mean
https://www.zotero.org/support/dev/web_api/v2/write_requests

It usually means the file has been modified since you last edited it and
zotero won't accept the attachment change because we would be overwriting
them.

I should update the app with better error messages, but I believe that's
expected behaviour.

**Comment by raffaem** [comment]
Hello, but I didn't change the file on Zotero

I import the PDF in the library using Zotero dekstop version. Then I update Zoo for Zotero to download the PDF. Then I open the PDF on the tablet and annotate it. Then I try to upload the annotated bersion wiht Zoo for Zotero and get this error.

After some more trials it finally works, generally.

It is Zotero API

**Comment by dkoguciuk** [comment]
Hi @mickstar and @raffaem, 

I've had the exact same problem a couple of times already and trying later actually worked.

Best,
D

**Comment by raffaem** [comment]
Any solution to this? :)

**Comment by dkoguciuk** [comment]
Now, I am not able to upload anything. I am constantly getting this: `Server Response: 413 null`

@mickstar do you have any tips on how to solve this? I've annotated more than 10 papers using Zoo for Zotero and I really don't want to lose it :smiley:

**Comment by mickstar** [comment]
Someone had a similar issue and the problem was related to not enough
storage space on zotero's servers.

I recommend grabbing the annotated files manually if you don't want to lose
them.

**Comment by raffaem** [comment]
I have the unlimited plan and get this error from time to time

**Comment by mickstar** [comment]
413?

412 is what you were referring to earlier, and that's precondition failed, related to mismatched file versions

**Comment by mickstar** [comment]
I think I need to update the error messages to make it more clear what's going on. A lot of these server errors are out my hands.

**Comment by raffaem** [comment]
No I'm getting the error I reported, so 412

@Daniel can we open a new issue if the error message is different? :)

**Comment by dkoguciuk** [comment]
Ah, yes, I'm sorry, I've mixed two different errors. And yes, I am probably out of space, because annotations take a huge amount of space. Sorry for the confusion!

**Comment by raffaem** [comment]
so can we fix this or improve the error message, so that Zotero can fix on their side if it's their issue?

We can post donations if they are needed :)
