### ISSUE TITLE
Syncing PDFs with a custom WebDAV cloud respository

### ISSUE THREAD

**Issue by mmbannert** [mickstar/Zoo-For-Zotero#144]
Hi,

I find this app extremely promising and I'm impressed that it is just one person doing all the work. Keep it up!

Unfortunately, this is not exactly useful to me at the moment *yet* because I do not have enough storage space on zotero for my library. I therefore have to keep all my files in my institution's cloud and use WebDAV to synchronise them across computers. Now, I would find it invaluable if I could also sync them to my tablet.

I have been using Mendeley until recently when Elsevier turned it pretty much unusable for me by discontinuing their app. Their mobile app in fact was one of the main reasons to get a tablet in the first place. So far zotero seems to be a promising alternative provided that there will be an accompanying app.

Cheers,
Michael

**Comment by mickstar** [comment]
WebDAV is supported, go to settings to configure.

**Comment by mmbannert** [comment]
Oh, does it? Ok - in that case I suppose that it just does not seem to work properly for me. I thought that option in Zoo was just for syncing annotations. And I erroneously assumed that this was working fine.

But I now realise that I apparently failed to set it up properly on my first attempt. It kept testing the connection for ages and it afterwards gave me:

`Error connecting to webDAV server
Error setting up webdav, message:
com.thegrizzlylabs.sardineandroid.impl.SardineException:Error
contacting https:[[webDAV address]] (401 Unauthorized)`

So it seems that setting it up does not work for me. And those entries that I am able to see are those from zotero itself (and not from my personal cloud repository).

Sorry about the confusion!

Cheers,
Michael

**Comment by mmbannert** [comment]
True! It now works for me as well. Not sure what I did differently this time unfortunately. Thanks for your reply and good luck with this nice project!
mb
