### ISSUE TITLE
Increase the timeout for webdav synchronisation

### ISSUE THREAD

**Issue by AMR-KELEG** [mickstar/Zoo-For-Zotero#157]
Hello,

I am starting to fall in love with Zotero thanks to this application but recently, I have been having problems with uploading attachments to WebDAV due to timeouts.
Could the timeout value be a configurable option in the app's settings/configuration?
I would have loved to do it but I am not an experienced mobile developer and I don't really know how to build Kotlin projects so I won't be able to test it even if I managed to code it.

Thanks 😄

**Comment by mickstar** [comment]
thanks for the issue. the next release will have this feature.

**Comment by AMR-KELEG** [comment]
Thanks!
