### ISSUE TITLE
question about recommended workflow

### ISSUE THREAD

**Issue by min-xu-ai** [mickstar/Zoo-For-Zotero#164]
I have a boox tablet and I have read from a blog that this app can be used to improve the Zotero/zotfile/tablet workflow. However, I didn't find any details on it. Can anyone provide more details on the workflow of Zotero/zotfile/zoo-for-zotero/boox tablet workflow.

Specifically, with this app, do I need to do "send to tablet" and "get from tablet" actions from zotfile plugin like that on the desktop (before and after pdf annotation on the tablet)?

Much thanks!

**Comment by mickstar** [comment]
Recommended would be to host the attachments on a webdav server (or zotero
if you don't mind the storage limitations)

And to use zotero account sync to sync the metadata.

If you want everything on the device, use the attachment manager to
download everything. And it should cache when you try to open files.

Zotfiles isn't appropriate for this app

**Comment by min-xu-ai** [comment]
Great. This is what I was looking for. Thanks for fast reply!
