### ISSUE TITLE
App not displayed in Google Play Store for devices running Android 14

### ISSUE THREAD

**Issue by rayjolt** [mickstar/Zoo-For-Zotero#188]
# Summary
On my device running Android 14, the Google Play Store does not list Zoo for Zotero; if I search for it directly I get a message saying that the app isn't available for my device because it was made for an older version of Android.

# Environment
- Phone: Google Pixel 7a
- Android version: 14

# Screenshot
![Screenshot_20231214-001316](https://github.com/mickstar/Zoo-For-Zotero/assets/5244112/880abf1f-322f-424b-90df-44f3270410b0)

**Comment by rayjolt** [comment]
I am guessing that some of the [Android 14 behaviour changes](https://developer.android.com/about/versions/14/behavior-changes-14) are impacting this app, although I don't have enough experience with Android development to easily say what changes are to blame.

**Comment by mickstar** [comment]
should be resolved

**Comment by rayjolt** [comment]
Thanks! I was able to install the app.
