### ISSUE TITLE
crashing on scan: GMS unable to scan barcode

### ISSUE THREAD

**Issue by caedmon5** [mickstar/Zoo-For-Zotero#189]
This is a new issue after a ui update last night. The app crashes when you choose the scan option, with a warning that "GMS is unable. To access the bar..."
![Screenshot_20240114_113150_Software update](https://github.com/mickstar/Zoo-For-Zotero/assets/1468536/3f790318-2aa7-4b9f-87e4-091ca0fa81cc)

**Comment by caedmon5** [comment]
![Screenshot_20240114_113240_One UI Home](https://github.com/mickstar/Zoo-For-Zotero/assets/1468536/a921b0a4-900b-41be-bf04-7fe62e798e84)

**Comment by mickstar** [comment]
i removed the barcode scanner in the latest release, it will try to open zxing an open source app if you use this function

**Comment by caedmon5** [comment]
Thanks for this. Does that mean there's a way of letting it know what to open.

----------------------------------------------------------------------------------------------
Daniel Paul O'Donnell, PhD
Department Chair and Professor of English
Member of the Academic Staff of the University Library
President, Confederation of Alberta Faculty Associations<https://cafa-ab.ca/> (CAFA)
Past President, University of Lethbridge Faculty Association<https://www.ulfa.ca/> (ULFA)
Editor-in-Chief, Digital Studies/Le champs numérique<https://www.digitalstudies.org/>

Humanities Innovation Lab<https://Humanitiesinnovationlab.ca>
Department of English<https://www.ulethbridge.ca/artsci/english>
University of Lethbridge<https://ulethbridge.ca>
Lethbridge Alberta T1J 2X5
Canada

Tel. +1 (403) 329-2377

***@***.***?anonymous&ep=signature>         Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
