### ISSUE TITLE
Bug(?) in "Sort by date added"

### ISSUE THREAD

**Issue by komorin95** [mickstar/Zoo-For-Zotero#19]
Thank you all for developing a truly helpful app.
I've found an unexpected behavior in the version 1.5a, which is uploaded to Google Play on 12 Nov 2019.

I'm using my Amazon Fire HD 8 (2017) with Android 5.1.1, with the Google Play app installed from an apk. (So this may come from my unusual environment.)

I've installed Zoo for Zotero to it through Google Play, and succeeded in syncing my Zotero library and some attachments.
However, when I
1. tap on the button at the top-right corner like ▼,
2. tap on the button on the top-right in the dialog shown up,
3. select "By Date Added" in the list shown up,
4. and tap on the "SUBMIT" button,
something unexpected happens.

- The list is instead sorted by title.
- If I go to the Settings, the library sorting setting says it is "unspecified".
- If I tap on the ▼ button again, the button in the dialog says "By Title".

Actually, it doesn't spoil the functionality, because instead I can use the Settings to make the list sorted by the date added.
But I'll be glad if this is fixed.

**Comment by mickstar** [comment]
Thank you for this bug report. it was a silly error
I have fixed it 4445eb9c3d36f06129c1d5671d7d7d0adc98d9bd on my dev version
and it will be live in the coming weeks.
