### ISSUE TITLE
Barcode scanner not working on pixel 6

### ISSUE THREAD

**Issue by Alasdair-Munday** [mickstar/Zoo-For-Zotero#192]
This was working fine until recently but the zxing barcode scanner isn't supported on pixel 6. 

This means when I attempt to open the scanner it says the app isn't installed but there is no way to install it

**Comment by mickstar** [comment]
how unfortunate..
I removed the google barcode scanner as many phones from china do not have access to the google vision library
and i wanted the app to be fdroid compliant

I think the best course of action is to include zxing as a library, it will double the APK size from 9MB to 15MB but this seems acceptable in 2024

**Comment by mickstar** [comment]
ok resolved in #195 
you will see it in the play store within a week.
