### ISSUE TITLE
Dark Mode Setting No Longer Working

### ISSUE THREAD

**Issue by jay-sf** [mickstar/Zoo-For-Zotero#193]
Hi mickstar,

Thanks for the excellent Zotero viewing app on smartphones. Recently, I noticed the app doesn't adapt to my phone's dark mode anymore (Zoo v3.1, Android 12, Samsung Galaxy S10e). Could you check this issue to help protect my eyesight?

Thanks, jay-sf

**Comment by mickstar** [comment]
Thanks for the bug report, i have submitted a fix in #194
