### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by natebragg** [mickstar/Zoo-For-Zotero#197]
The last release was 3 years ago, and there have been a bunch of commits since then.  Please cut a new release (including the apk file, so you don't need to get it off of the play store, or even better, put it on f-droid).

**Comment by mickstar** [comment]
There’s already a new release on the play store as of 2 months ago.

I’ll upload an apk tonight (6 or so hours)

F-droid is a good idea, I recently removed all the Google analytics so now
no blockers I just have to register there. Ill look into it when I have
spare time

**Comment by mickstar** [comment]
https://github.com/mickstar/Zoo-For-Zotero/releases/tag/v3.1a
