### ISSUE TITLE
Feature request: reversing the sorted order

### ISSUE THREAD

**Issue by komorin95** [mickstar/Zoo-For-Zotero#20]
It seems useful if we can reverse the order for sorting the list.
In particular, when sorting "By Date Added", one might want to sort the list in the newest-first way.

**Comment by mickstar** [comment]
It's possible but the way i coded it makes it a bit tedious. I will implement it when i have time, but not in the near future.

**Comment by mickstar** [comment]
completed in #22 
Thank you for the issue komorin!
