### ISSUE TITLE
PDF Two way syncing

### ISSUE THREAD

**Issue by mickstar** [mickstar/Zoo-For-Zotero#23]
Would be nice to have the app detect changes made to pdf attachments (such as highlighting,annotations,etc) and offer to upload the modified pdf back to zotero's servers.

from initial testing, some challenges include:
Only certain PDF editors play nice (like Xodo)
Adobe acrobat saves the modified pdf in a new file so changes cannot be detected

**Comment by fkgruber** [comment]
Yes that would be the most important feature to add. XODO is one of the best pdf editors in android. Seems to be fine if it only works with pdf editor that modify the pdf directly. 
Is this something that you plan to add anytime soon?

**Comment by mickstar** [comment]
It is the next thing I plan to do. Right now my plan is to keep a list of all opened attachments, and then the next time the user opens the app I go through the list and check the respective PDFs for modifications via MD5 and create a prompt offering to upload the pdfs.

**Comment by mickstar** [comment]
I have found the zotero api for uploading pdfs difficult and rather confusing. At this stage I am unwilling to spend the time to work it out. This may change if the app gets stronger user growth or hopefully someone assists with the technical aspect of uploading pdfs.

**Comment by fkgruber** [comment]
that is too bad. That explains why there isn't a single Android that can upload the modified pdfs to the zotero servers.

I see the reference at:
https://www.zotero.org/support/dev/web_api/v3/file_upload

Would it help to get a python example of how the pdf upload work?
thanks
Fkg

**Comment by mickstar** [comment]
It would, i believe pyzotero can upload so maybe i should have a look at that.

**Comment by mickstar** [comment]
**Good News**
Made a lot of progress in 3f00a4ab152cc5570bc97de829af7033bc5972be

I have attachment resyncing **working**, though at this stage it requires whole file reuploading. this can be improved with file deltas in the future.

The process took a lot of engineering, uploading PDFs using zotero's API requires 3 different network calls, all depending on each other.

Anyway, these changes will take some time to join the master as it's buggy

**Comment by fkgruber** [comment]
Wow that is great news! 

Most paper's pdfs are pretty small. I don't see anything wrong with reuploading the whole pdf. Maybe for complete  books the pdf may be bigger but I can't imagine people use zotero for books.

thanks a lot!
 can't wait to try it out.

**Comment by mickstar** [comment]
Please try the beta version of the app
https://play.google.com/apps/internaltest/4701222546314683412

given the amount of complexity added to the app i expect a few issues will come up

**Comment by mickstar** [comment]
added webdav syncing in #45

**Comment by fkgruber** [comment]
Hi Michael,
I have an issue  in which Zoo does not detect that the pdf changed. If I drag down to sync, the pdf gets overwritten with the version in the server. I wished there was a way to force upload of the pdf of a specific article. Maybe press and hold or something.

**Comment by mickstar** [comment]
Can you verify that the specific file in the zotedo directory has changed,
and not a copy of the file.

The app should detect changes,
How it works is every time you open a pdf,
It adds it to a list

Every time you start the app, it goes through this list and calculates the
MD5 checksum of the pdf and checks for change.

I can't guess why it wouldn't work.

**Comment by fkgruber** [comment]
I went to the android/zoo directory/cache and open the pdf there and it is definitely changed. 
I then went to zoo try opening the pdf again and it says your local copy is different to the servers's would you like to redownload the server's copy. I does not give any option to upload to server. perhaps an extra button would be nice when you choose whether to upload or download?

Just for more clarification, I'm trying this on a eink reader so I need to use a  specialized pdf editor which works better than xodo given the eink constraints. Anyways,  when you first make annotations it save them it some database then when you have an option to embed the annotation in the pdf. SO it works different from xodo where the changes happen right away. Maybe it has something to do wi the issue.

**Comment by mickstar** [comment]
Yes that would explain the issue.
Since it only checks the file after opening it never detects the changes.

A simple solution would be for you to press no to redownloading, then hit
back to go to zoo and it will offer to upload.

**Comment by fkgruber** [comment]
I tried that and this is what happened:
 pressed no
open the pdf with xodo I can see the annotations
press back to go to zoo
I did not get any upload message
tried opening the pdf again
did not say anything, open it xodo. annotation is gone.
It seems to have downloaded the copy from server and replaced the annotated one.

**Comment by mickstar** [comment]
I see, that sounds like a bug.

Im on a bit of a break from coding right now but when I get back on the
project I will reexamine the downloading code and see if I can find a
erroneous download call.

**Comment by fkgruber** [comment]
thanks

**Comment by theotheo** [comment]
I try to sync annotations on group library pdf and I observe the same behavior: it nothing happens. I don't see any messages and it looks like nothing uploaded.

**Comment by mickstar** [comment]
Group annotation syncing is currently disabled in the app.

**Comment by fkgruber** [comment]
Hi Michael, 
any hope of having an option to upload attachment to server (in addition of the current option of redownload it) when it detects changes in the pdf? 
I think that would pretty much fix my issue with the ereader.

thanks
FKG

**Comment by mickstar** [comment]
It's doable.

I will try find time on the weekend to implement it

**Comment by fkgruber** [comment]
Thanks!

**Comment by fwmetzler** [comment]
I also have trouble re-uploading annotated PDFs. 

I use Xodo on an Android tablet and I use the Zotero paid storage plan. I'm not sure how I should leave Xodo for the PDF to upload -- do I just press the back button or should I close the open PDF in the top tab bar? In any case, I don't get any message and my changes seem to be lost. When I reopen the PDF in Zoo, I get the original PDF with no annotations. Any advice? Thanks a lot

**Comment by fwmetzler** [comment]
Just letting others know: this seems to be working now with the latest version. Thanks!

**Comment by theotheo** [comment]
@fwmetzler Sorry, but which version do you mean?

**Comment by camayl** [comment]
@mickstar reuploading annotated pdf's works on my phone (android 9) perfectly.

however it's simply not working on my Samsung Galaxy Tab S (android 6.0.1) where I really need it. Whenever I annotate in Xodo and close the file, changes are not saved (so annotations are lost on reopening the pdf on same device), nor prompted to reupload.  

Could you think of a possible fix for this? I would love to generously support the app if I could use it on my tablet, it would be a gamechanger for me!!

**Comment by fwmetzler** [comment]
Sorry to revive this issue. I keep running into similar problems as described above, even though now I have a completely new/different tablet than before (now: Galaxy S6 Tablet with Android 11 with the latest version of Zoo for Zotero). 

Downloading PDF attachments works fine consistently and reuploading after changes initially too but after some time of use, the following happens: when I make a change and confirm the prompt to reupload, I get the message:
"Error uploading Attachment" and in the second row "java.lang.Exception: Server Response: 412 null"
From then on, this is the case for every PDF that I try to reupload (even though downloading continues to work fine). 

Interestingly, a reboot of the tablet solves the problem temporarily. But after some time it reoccurs.

Any thoughts? Thanks a lot.
