### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by FMuro** [mickstar/Zoo-For-Zotero#26]
Wow! I'm impressed with this app! It's the only Zotero app which really works, and I've tested many since I'm a Zotero user (many years). I wanted to say thanks and to offer my help. I'm not a technical person, just a user, but I can help with testing and user experience. I'm using it with webdav. Let me suggest to make a post about this app in the Zotero forum and also to offer a way to contribute financially to its development. Thanks again!

**Comment by mickstar** [comment]
Thank you for the kind message!
At this stage I don't need/want any donations/monetary rewards. This is very much a passion project for me.

Of course, any user experience suggestions are always welcome and this issues section is a good place to post them.

I do consider the most valuable contributions as being technical, though unfortunately this is a rather niche project and android development is rather specialised.

**Comment by FMuro** [comment]
Good, I'll come back with some user feedback. In the meantime, please consider advertising this app in the Zotero forum so that it becomes included in the [Zotero for mobile](https://www.zotero.org/support/mobile) section
