### ISSUE TITLE
crashes at initial sync after item 2900

### ISSUE THREAD

**Issue by fkgruber** [mickstar/Zoo-For-Zotero#29]
Hi
I'm trying on a Galaxy note 10 + and the initial sync from zotero servers crashes at about the item 2900. I have about 7000 items to sync.
FKG

**Comment by mickstar** [comment]
yes, you are not the only one, seems my last update doesnt work on large libraries.

I'm investigating now but i suspect its some kind of running out of memory error related

**Comment by mickstar** [comment]
uploaded a fix, it will take google a few hours to publish the new version. Let me know if the error persists
