### ISSUE TITLE
Cannot setup WebDAV

### ISSUE THREAD

**Issue by traits** [mickstar/Zoo-For-Zotero#33]
For some reason, this always fails on my Android devices (multiple, Android 7 to 9). I get 

```
Error connecting to webDAV server

There was an error connecting to the webDAV server.Please verify the address, username and password.
```

I did so. All things are the same as with the official Desktop application, which works flawlessly on Windows and Linux clients. Any logs anywhere? Something else, I should check? Could be the http (not https) address of my webDAV server be a problem?

**Comment by mickstar** [comment]
Could be, make sure http:// is prefacing the address as it defaults to https. What android device are you using?

**Comment by mickstar** [comment]
I submitted a small change in 1573fa59d765f4574322ef013d395c666e7dd7e3 so it will print the error. Unfortunately this won't make it to the play store for a week+.

Please check and make sure your url does NOT end with a /
the app appends "/zotero" to all webdav urls, so
example.com/ would yield example.com//zotero which would fail.
It also appends HTTPS:// if it doesnt see a http as well though i suspect that isn't your problem.

**Comment by traits** [comment]
OK, also with a pure URL (no directory part, no trailing slash, explicit `http://`) the error remains. I'll wait for the Google Play update.

**Comment by mickstar** [comment]
I have found the bug, it is related to how android handles unencrypted traffic. By default cleartext communication is disabled, as such HTTP does not work at all. It would fix your issue if you are able to use HTTPS instead.

https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by traits** [comment]
> It would fix your issue if you are able to use HTTPS instead.

This has more ramifications. I am using self-signed certificates, sometimes causing problems with an application, including Zotero's official desktop client. Probably for this reason, he is supporting http. How these certificates behave on Android in general and Zoo-for-zotero in particular, I have no idea. I am a developer, but mobile is not exactly my turf. 
What I know is, they are not really rare and people looking for Zotero's webdav often do so, because they self-host one way or another. Unfortunately, these packages tend to provide no CA-backed certificates.

**Comment by mickstar** [comment]
Please try this version of the app and see if it fixes your issue.
https://play.google.com/apps/internaltest/4701222546314683412

**Comment by traits** [comment]
Nope (see attached images for error messages for http respective https ('Let's Encrypt' certificate)  case. I checked this on Android 9 (Moto One) and Android 7.1.1 (Lenovo tablet) devices.
![Screenshot_2019-12-12-13-04-49-660](https://user-images.githubusercontent.com/4024583/70713877-42164400-1ce7-11ea-9da4-a6063d71ca28.jpeg)
![Screenshot_2019-12-12-13-05-12-765](https://user-images.githubusercontent.com/4024583/70713878-42164400-1ce7-11ea-9013-318ecf00574a.jpeg)

**Comment by mickstar** [comment]
Ok, I believe the problem is in the webdav library I'm using, sardine, which doesn't let me allow for self signed certs. I will see if I can patch the library.

**Comment by mickstar** [comment]
alright try it again using the latest version i just pushed to the playstore.

**Comment by traits** [comment]
It's better now (authentification works). But I have a new problem, ([description here](https://forums.zotero.org/discussion/80499/directory-structure-webdav)). Where is Zoo for Zotero looking for zip/prop files - the servers root or explicitely the zotero directory beneath?

**Comment by mickstar** [comment]
It always looks at the zotero sub directory. It would be trivial to change however it only seems to be you with this issue. The desktop client has always used the sub directory for me.

**Comment by traits** [comment]
Mmmh, here it was never otherwise. I will see, what they say.

**Comment by traits** [comment]
There is another error now, though: I can replace the first part of my webdav URL by anything (even changing the name to something not-existent. Example: changing the existing `zotero.traits.de` into non-existing `bambule.traits.de`). Zoo will not complain and even returns '`Successfully added WebDAV.`'

**Comment by mickstar** [comment]
not a major issue in my opinion.
The server validation consists of `sardine.exists(address)`
bambule.traits.de is a valid webdav host so it returns true. connecting returns a 304
which apparently doesn't throw an error with the webdav library im using.
 
I don't consider this a serious issue and i'm unwilling to write custom code to properly
validate webdav connections.

**Comment by traits** [comment]
OK, I got some things straightened out in my hosters configuration. 

All my WebDAV clients (even zotero desktop) are working now with https. Zoo still cannot access attachements, very probably caused by the following auth issue, found in my error logs:

`AH01781: client used wrong authentication scheme `Basic': /zotero`

Would it be possible to support Digest mode?

**Comment by mickstar** [comment]
Something like described here?
https://github.com/lookfirst/sardine/wiki/UsageGuide#preemptive-authentication

**Comment by traits** [comment]
> Something like described here?

I found this too, but I'm out of my expertise here. The other thing I read is, that the combination HTTPS + Digest mode is common (even if HTTPS + basic mode is sufficient, if I understand correctly).
