### ISSUE TITLE
Feature Request: Tag Support

### ISSUE THREAD

**Issue by Shamp0o** [mickstar/Zoo-For-Zotero#34]
Would be nice to have the ability to add tags and filter items by tags like in the desktop client.

**Comment by mickstar** [comment]
Yes, i would like to implement that in the future. Thank you for the suggestion!

At this stage, I believe the search functionality takes tags into consideration so filtering can happen that way.

I would like to put tags on the sidebar view and have the user be able to switch between collections/tags view.

**Comment by rgfuller** [comment]
Search does not return tags in my tests.

**Comment by hlblade** [comment]
The tag supporting is a big advantage of zotero in compare with the alternatives like mendeley and endnote, hope Zoo-For-Zotero can support tags soon. 
And as rgfuller said, we can not search tags with the current search function.
Thanks  for your awesome  app and great work.

**Comment by markusritschel** [comment]
> Search does not return tags in my tests.

Neither for me. This would be nice to have. Best would be a real tag-support. But include tags in the search would already help. Is this possible to being implemented quickly?
