### ISSUE TITLE
Single touch should open the PDF while long touch should show the full info

### ISSUE THREAD

**Issue by dwellexity** [mickstar/Zoo-For-Zotero#36]
As most of us on phone are only trying to get a quick look on some paper, it might be helpful to make viewing attached files easier.

**Comment by mickstar** [comment]
Good idea, 
i will added a toggle in settings to enable this.

**Comment by mikolak-net** [comment]
@mickstar : 

1. might I suggest an alternative setting title, such as "Short press opens PDF"? 
1. there's a small inconsistency issue. When the setting is off, **both** touch **and** long press show the info. As a user, I would expect long press to open the PDF in this case.

**Comment by mickstar** [comment]
@mikolak-net 
1. Agreed, will do
2. regarding this, i am going to add the functionality of deleting items as well as setting the parent collection, which i was planning on putting in a dialog on long press as well as little buttons on the top of the item view.

**Comment by mikolak-net** [comment]
Re 2: sounds great. The primary context of the remark was that the long press and short press/touch should be duals in functionality, i.e. that - with the toggle reversed - one has the exact same functionality as the other, and vice versa.
