### ISSUE TITLE
PDFs downloaded but not opened

### ISSUE THREAD

**Issue by GeorgRamer** [mickstar/Zoo-For-Zotero#38]
Let me start by saying how great the app already is! Thank you for taking the time writing it!

The only issue that I have with it right now is that PDFs are downloaded (and stored on the device) but not opened. The files are stored inside of cryptically named folders in my download folder so they are quite hard to find after downloading, too. Is this the expected behaviour?

**Comment by mickstar** [comment]
No, the app should open the PDFs upon downloading/tapping.
There is a bug with Huawei devices whereby they don't respect the android standard for opening files and just crash. https://stackoverflow.com/questions/53853044/i-could-not-choose-pdf-file-in-android-8-oreo-huawei describes the problem. The main solution seems to be copying the file to the app folder after downloading which seems wasteful but i will implement this solution for the next update.

Regarding the folder structure, i recently changed it to mirror the Zotero desktop clients, which is 
{itemkey}/attachment.pdf . The reason for this change is for users that wish to copy/sync their zotero's  folder to their device so they can access the PDFs without downloading.

**Comment by dbonattoj** [comment]
Hello there,
Very nice app!

I'm not sure it is the issue here, I have the same bahaviour in Samsung Galaxy Tab s3!
At the moment I go to the folder by hand and find the PDFs.

Is there a way to access application log files?

Thanks for the good work!

**Comment by mickstar** [comment]
Yes, you could connect it to a computer and use logcat or try one of the
logcat apps on the Play store.

So as I'm understanding it, the app downloads attachments but doesn't open
them? And there is a pdf reader app installed?

**Comment by GeorgRamer** [comment]
Yes. There is a pdf reader app installed. I am on a Pixel 2, if that helps.
I will see what logcat outputs and the report back.

**Comment by mickstar** [comment]
oops found the bug, it occurs when webdav is enable and was due to bad logic
fixed in 531f70b8cde9d56c26c7e59ea40e7bcf38cbf059

**Comment by traits** [comment]
> Regarding the folder structure, i recently changed it to mirror the Zotero desktop clients, which is
> {itemkey}/attachment.pdf . The reason for this change is for users that wish to copy/sync their zotero's folder to their device so they can access the PDFs without downloading.

This is a good thing. It makes a satisfying workaround for me regarding webdav (#33) issues. Please don't change this.

**Comment by malla8848** [comment]
I am facing the same issue when I enabled webdav. Seems like new version received previous bug related to pdf not opening when using webdav. I hope it will be resolved so that pdf can be opened. Thank you
