### ISSUE TITLE
Add a privacy friendly version to f-droid

### ISSUE THREAD

**Issue by ashwinvis** [mickstar/Zoo-For-Zotero#39]
Zoo-for-Zotero looks good from screenshots, but it does not meet the [Inclusion Policy](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy) since Google Analytics are used in the app. How practical is it to have a build which disables it? When disabled the package can be [requested to be added to f-droid](https://gitlab.com/fdroid/rfp).

**Comment by mickstar** [comment]
It's non trivial as there's a bunch of firebase.logEvent calls scattered in the codebase. Also I believe they automate compiling it themselves so it's not as simple as building another variant, I would have to maintain a seperate repo, which I do not want to do

**Comment by ashwinvis** [comment]
I see. I am not familiar with how Kotlin works, so I do not dare suggest a solution. Thanks.

**Comment by funnyflowerpot** [comment]
The app looks really nice! However, I am not using Google Play, so I would also much appreciate a version on F-Droid. 

I understand the blocking issue here, but just wanted to signal that somebody else would be interested! :-)

**Comment by Hoeze** [comment]
Hey, another interested one here :hand: 

@mickstar Wouldn't it be possible to just disable google-analytics at compile time?
Then there is no need to maintain two separate repositories (nobody does that).

**Comment by mickstar** [comment]
Yes, I can have a different build variant that doesn't include analytics but I'm not sure if f-droid will compile it.

My understanding is that they scan the build.gradle for non free libraries before they compile it.

F-droid is not something I can just send an apk to, they need a git repo which they can compile

**Comment by Hoeze** [comment]
I'm pretty sure that's enough if you do not include any binary/proprietary dependencies in your build variant.
AFAIK many fdroid apps go this route, e.g. for disabling GCM.


> **Can I track users from my app?**
> 
> You can, but if you include any kind of tracking or analytics in your application (even sending crash reports) this must be something that the user explicitly opts in to - i.e. you ask them on first run, before sending anything anywhere, or there’s a preference that defaults to OFF. In all other cases, we may still include the app, but it will be flagged with our ‘Tracking’ AntiFeature, which means users will only ever see the app if they choose to view such apps.
> 
> Additionally, note that third party analytics libraries that come in the form of proprietary software (for example, Google Analytics or Flurry) are not acceptable here.

**Comment by aadityabhatia** [comment]
Please note that the app does not have a privacy policy or a way to opt-out. Curious as to what is collected and how that aligns with GDPR measures regarding personal information that is potentially collected (Google Analytics ID, Client ID, IP address etc.) in the process.

Some indication in app of what is being collected will be greatly appreciated. I was completely unaware of the use of tracking / analytics until I looked at this repo.
