### ISSUE TITLE
Crashes at downloading item 5300 of 7574

### ISSUE THREAD

**Issue by fkgruber** [mickstar/Zoo-For-Zotero#40]
Hi
I'm was trying to use zoo on a ereader (onyx note) and it crashes when downloading the articles.  Specifically at article 5300.

thanks
FKG

**Comment by mickstar** [comment]
Couldn't find the crash in my analytics console but if I had to guess it's probably due to memory allocation.

I should implement partial downloading so if it crashes you can pick up where you left off.

**Comment by fkgruber** [comment]
thanks for fixing this!
