### ISSUE TITLE
can't open linked attachments with custom sync path

### ISSUE THREAD

**Issue by lebedov** [mickstar/Zoo-For-Zotero#41]
When I tried setting the custom attachments path in Zoo to a local folder on my Android device that I sync with a folder on the cloud containing my linked attachments, I was unable to open those attachments from within Zoo. Would it be possible to update Zoo to be able to use the custom path to find and display linked files (as Zotero is able to do on the desktop)?

**Comment by mickstar** [comment]
too difficult to implement my opinion.
If you are linking to custom paths in say dropbox, just use dropbox to access the PDFs

**Comment by jundurraga** [comment]
Dear Mickstar, 
Thanks for your efforts on developing this app! 
This is just a comment with regards to the use of linked files. I think many Zotero users combine zotfile + zotero to access their files across devices. Thus, having the option to set a relative path to try finding linked files would be great added value for your app and for all Zotero users with android devices. I'm not sure how complicate may this be in android, but a simple tweak would be to check if the file is linked and if the relative path has been set to try finding and open the document. 
Zotero database has a table called itemAttachments with the "path". All linked files are set as "attachments:relative_path_to_file"
not sure if that would be helpful when using the Zotero API though. 
Cheers,
Jaime

**Comment by mickstar** [comment]
The 2.6 update I just pushed has some code for handling relative path
linked attachments but just using zotero's implementation. You need to use
"custom path" for attachments for this to work.

I may have to make some adjustments to support zotfile as well, but that
shouldn't be too difficult.

**Comment by jundurraga** [comment]
Great! happy to give it a go as a beta user :)
