### ISSUE TITLE
downloading all attachments?

### ISSUE THREAD

**Issue by zampanoo** [mickstar/Zoo-For-Zotero#42]
Hi, really pleased to find a working android app for Zotero - now I should be able to carry around my research library! Thanks a lot!
Is it possible to download all attachments in one go? I am able to access my webdav repository but it seems prohibitive to download each single attachment separately, by going through the entire list!
Is a bulk download possible? Thanks!

**Comment by mickstar** [comment]
Not possible at this stage but I would like to add this feature. Currently the idea is "On demand" but i understand that some users don't have mobile data available or would prefer using WIFI.

I would like to rewrite the way items are stored first and i have taken a bit of a break from this project but i will dedicate some time soon.

**Comment by zampanoo** [comment]
Thanks for your quick reply and for taking my suggestion into account. You describe the reason for having all pdfs on the device very well: especially when traveling, there is not always a signal. The idea to have my library available offline on a portable device is really appealing - I am looking forward to any progress!
[I haven't got a clue about programming but maybe it would be possible to copy an existing downloaded zotero library across to my android device instead of downloading everything once more? Probably not! :-) ]
Happy new year!

**Comment by mickstar** [comment]
actually yes!
It mirrors the zotero desktop file structure so if you copy the folder with
all the itemkeys it should work.

**Comment by zampanoo** [comment]
Ha - great! And into which zoo-folder do I need to copy the database? Thx.

**Comment by mickstar** [comment]
Copy the zotero/storage folder onto your phone and set the attachment
location as being "Custom" then point to the storage folder

**Comment by zampanoo** [comment]
Thx, done - does work. This approach might be worth mentioning somewhere to help others.

Glad I spent a day or so flashing Android 7 onto an old samsung tablet with Android 4, in order to be able to run ZoofZ...

Thanks a lot!

**Comment by mickstar** [comment]
Feature added in #45 
expect in play store by end of week

**Comment by taylor9martin** [comment]
Hi - I'm new to Zoo but thus far love the app. I had the same question/desire to be able to access the PDFs even when not connected. From what I read above this is possible? I am still unaware of how to do this. Can you please provide a bit more detail? And can you please clarify whether 'Copy the zotero/storage folder onto your phone' is a one-time thing or whether as I grow my zotero library (on Desktop) I will have to make new copies on my phone for Zoo?
