### ISSUE TITLE
Unable to download some djvu files

### ISSUE THREAD

**Issue by dbonattoj** [mickstar/Zoo-For-Zotero#47]
Hi,

In my library I have a mix of papers and files, often I use the djvu format as it is lightweight compared to pdf.

Zoo do not let me download those files (tested on my phone and my tablet) but the files open without problem in the desktop app.
They are located in a WebDAV server.

I guess this should be an easy fix :)

Bests,

**Comment by mickstar** [comment]
Yes, I will add it to the next release

**Comment by mickstar** [comment]
added to 2.2b release currently on playstore

**Comment by dbonattoj** [comment]
Thanks !

Effectively I now have a way of downloading the djvu If I do a file search and click directly on it.

But if a click on a document containing a djvu file it opens me the property window instead of downloading and even from there if I scroll down and I click on the file it doesn't download it. It does nothing.

However I consider it a less important bug right now as using a search on the filename I can open the file :)

So, clicking on this is ok
![Screenshot_20200120-015843](https://user-images.githubusercontent.com/28501597/72691847-ad460800-3b28-11ea-8d23-9e125c9a4443.png)

But clicking on this opens the prop menu
![Screenshot_20200120-015852](https://user-images.githubusercontent.com/28501597/72691819-8a1b5880-3b28-11ea-82c1-755844658e6d.png)

And from the prop menu I can't download the file, it does nothing
![Screenshot_20200120-015916](https://user-images.githubusercontent.com/28501597/72691825-93a4c080-3b28-11ea-9b23-bce1d34b6e30.png)

Anyway thanks for all the good work !
