### ISSUE TITLE
library contents no longer show after update (except group libraries)

### ISSUE THREAD

**Issue by zampanoo** [mickstar/Zoo-For-Zotero#49]
Hi Mickstar,

thanks for the update. I installed it on two devices, a phone with Android 8 and a tablet with Android 7.1.1.

Unfortunately, in both cases only the collections/subcollections show but there is nothing inside -  they are empty. When refreshing either a collection or the entire library, I can see the horizontal strip work for a second but then the suggestion to refresh is displayed again. However, group libraries do work as they should; upon refreshing them individually, the items are downloaded correctly.

All worked fine for me before the update.

Is there a setting hidden somewhere for a dark mode as shown in the screenshots on GooglePlay?

Thanks! Stefan

**Comment by mickstar** [comment]
I'm sorry about that.
I changed the way items are stored and wrote some transitional code to move
storage. This code seems to be somewhat inefficient and crashes from taking
too much memory on many devices. The crash leaves the app in a
unpredictable state.

You will need to clear app data to fix this.

**Comment by dbonattoj** [comment]
+1 for this issue and it's solution on both my tablet and phone.

Cleaning the storage of the app and reconfiguring it (it's very fast) let you load again all the files :)

**Comment by zampanoo** [comment]
No need to apologize! Got it to work as well on both tablet and phone upon clearing data. Thanks, should have thought of this myself.
Currently no luck with establishing connection to my webdav storage for some reason  (error message: no handshake) but I am probably doing something wrong. Will try again later.
