### ISSUE TITLE
epub ?

### ISSUE THREAD

**Issue by fkgruber** [mickstar/Zoo-For-Zotero#53]
Hi
How does the epub work? Is there a way to store annotations?
I'm not away of any epub reader that store annotations inside the epub (as in pdfs).
thanks
FKG

**Comment by mickstar** [comment]
That was just meant to mean the app can download epubs as attachments.
Someone had emailed me earlier requesting this be added.

Of course there is no reason why changes couldn't be synced, the code is
indifferent to filetype. Though I believe you are correct that epub
annotations is not a thing.
