### ISSUE TITLE
Can't copy the content of notes.

### ISSUE THREAD

**Issue by felipehw** [mickstar/Zoo-For-Zotero#55]
When I open a note, just to see its content ... I can't copy parts of the text.
I wanna read something of these notes and eventually use some parts outside of the app.

**Comment by mickstar** [comment]
i will make the text selectable in the next release.

**Comment by mickstar** [comment]
added here 6e99f7db39e761bc1251f176309f4906386c0a0d
should arrive in play store within a week.

**Comment by felipehw** [comment]
Thanks for this improvement!
