### ISSUE TITLE
WebDAV: Support Digest authentication method

### ISSUE THREAD

**Issue by modestos** [mickstar/Zoo-For-Zotero#59]
Hi,
Thanks for the great app.

It appears that only Basic authentication is supported at its current version.
I get:
[auth_digest:error] [pid 26151:tid 139676413286144] [client XXXX] AH01781: client used wrong authentication scheme `Basic': /DAV/zotero

Is there a workaround on this?

All best,
Modestos

**Comment by mickstar** [comment]
Yeah Its a limitation with the library I'm using, sardine-android.

For what it's worth, basic with https is sufficiently secure if you are able to reconfigure your webdav server.

**Comment by modestos** [comment]
Thanks Michael, clear enough.
