### ISSUE TITLE
Redesign of Zoo-For-Zotero App Icon

### ISSUE THREAD

**Issue by axre** [mickstar/Zoo-For-Zotero#68]
Hey @mickstar,

i currently refresh my graphic design skills and have time for a small project. As i really like to use this app, i thought maybe theres some interest for a different icon. If you (or any body else?) have any ideas for the icon based on [Google Play Icon Design Specifications](https://developer.android.com/google-play/resources/icon-design-specifications) feel free to drop them below. 

Current Design:
![grafik](https://user-images.githubusercontent.com/16156320/80997554-c5286a00-8e41-11ea-9593-3858187401c9.png)

Whats in the icon?
What colors to use?
Text?

I have some Ideas, which i will keep until some sketches.
If you're not at all interested - thats also ok, no pressure from my side.

**Comment by mickstar** [comment]
Great initiative!
Graphics certainly could do with an upgrade. It's quite a big task though, if you look at

**Comment by axre** [comment]
Well, i guess there was a mistunderstanding here. I meant the major app icon.
However i agree that the normal icons also could need some work, but i dont think its needed to change them. I will create a new issue for this.

**Comment by mickstar** [comment]
Hmm perhaps it could be improved.
I'm open to any kind of design. Try not to imitate the official zotero icon too much as I would be concerned with copyright infringement.
