### ISSUE TITLE
Item types "Case" and "Statute" displayed with title "unknown"

### ISSUE THREAD

**Issue by StianOby** [mickstar/Zoo-For-Zotero#7]
Items of the item type "Case" (court cases) are displayed with "unknown" as their title. That is probably because there is no "title" field for cases -- the field is instead named "Case Name".

Items of the item type "Statute" (legislation) are also displayed with "unknown" as their title. Similarly to cases, there is no "title" field for "Statute" -- it is instead named "Name of Act".

_(This issue may also occur with other item types. These are just the ones I have noticed so far.)_

**Comment by mickstar** [comment]
Resolved in 60f384d288a189ce914142369328b2c8fe2d3255
