### ISSUE TITLE
Only two collections displayed

### ISSUE THREAD

**Issue by StianOby** [mickstar/Zoo-For-Zotero#8]
I have a large Library of 3000+ items, organized into a myriad of collections. However, in the app only the first two collections on my list appear (+ unfiled items).

The screenshots used for advertising the app also only shows two collections. Perhaps there is an error in the code limiting the list to only two collections?

**Comment by mickstar** [comment]
Thank you. The app only downloaded the first 25 collections so for people with more than 25 it was not fully syncing.
fixed in cd2ad11
