### ISSUE TITLE
The app isn't usable with large db: difficult to install and to run (app crash during installation and after)

### ISSUE THREAD

**Issue by WiliTest** [mickstar/Zoo-For-Zotero#87]
I did struggle with my cheap phone to install/run the app (I did send you several reports today with a Redmi 7A, 2gb of RAM) ). It finally manages to install and run it but it's not really usable. (My friend who has the same phone has the same problems).

**Information of (my) zotero**

- I don't upload any attachment to Zotero, I just use the Zotero DB which contains10000 items, some of them are large notes. On my PC my DB (zot sqlite) is 100Mb.

**A) problems during the installation/download**: 

 1. MIUI kills the app after a few minutes (even when we disable the battery saver on the app). But it's manageable by disabling the lock screen and by keeping the app alive by clicking regularly on the screen while it downloads (≈10min).

2. Then, the app gets stuck when the download is complete or nearly complete (eg: "downloading 10000 of 10000"), after few minutes a popup appears "the app is not responding, want to wait?". After clicking on wait, a few minutes later the same popup appears, etc. for 3 or 4 times. Then the app is showing the db.

 **B) problem to run it**: 

1) After opening the app I searched for an item that crashed the app (it might require to much RAM): the app is frozen and only display a black screen. I needed to lock the phone to kill it.

2) When (re)starting, the app often gets stuck on "loading your library" (but nothing happens), the menu isn't responsive. It takes more than 5mn to open it. If I switch to another app during this delay, Zoo will crash (the app will be a black screen). I'll then need to lock/unlock the phone to kill it.

**Comment by mickstar** [comment]
Not much to be done here. The app isn't efficient with memory but improving
this would require basically a rewrite.

For large libraries on low-end phones, I would recommend the web library +
zotfile
