### ISSUE TITLE
Synchronization takes a long time, cannot use the app while syncing

### ISSUE THREAD

**Issue by StianOby** [mickstar/Zoo-For-Zotero#9]
_(This is probably more of a feature request than a bug report.)_

From time to time the app wants to sync when opening. Since I have a large library (3000+ items, meaning 7000+ things to sync), this takes several minutes. I cannot use the app while waiting for it to sync, nor can I cancel the sync and open the app. I therefore cannot rely on the app for looking up things quickly on the go, as I might have to wait an eternity for it to sync.

Ideally, syncing should be asynchroneous, in the sense that it would sync in the background while you use the app.

**Comment by mickstar** [comment]
sync time should be reduced by only selectively syncing modified content #13 .
This won't reduce the initial sync and sync times are constrained by the zotero servers which I can't help.
