### ISSUE TITLE
Groups don't sync anymore

### ISSUE THREAD

**Issue by graidl** [mickstar/Zoo-For-Zotero#90]
Since recently groups do not sync at all anymore. When choosing a group, the title of the page changes and occasionally the progress bar for syncing appears, but only the collections and content of "My Library" are finally shown. "Reloading" does not change anything. I also reinstalled the app from scratch and checked the all the permissions of the Zotero key, r/w access is granted also for the groups. Any idea?

I didn't use the app that much in the past, but I am quite sure that this still worked some days ago.

**Comment by mickstar** [comment]
Yes, i can recreate the problem. Will fix asap

**Comment by mickstar** [comment]
fixed in 9e7c8ad0e8d5cfbb270f346d2e352aecf786cd85
I just pushed it to the android store
