### ISSUE TITLE
Can not refresh library from storage

### ISSUE THREAD

**Issue by cdb0y511** [mickstar/Zoo-For-Zotero#91]
Hi, I copy my storage folder from pc to matepad, and then set custom path to the storage folder.
But, it still says "this catalog is empty ." What am I miss?
https://github.com/mickstar/Zoo-For-Zotero/issues/42#issuecomment-570552779
zoo has permission for storage.

**Comment by mickstar** [comment]
Are you using zotero sync?
This app doesn't load zotero databases, it just syncs with zotero's servers

**Comment by cdb0y511** [comment]
How can I work on offline mode?
I think must sign in.

**Comment by cdb0y511** [comment]
I may misunderstand, It must sync the databases online but can load attachment offline.

**Comment by cdb0y511** [comment]
perfect works. 
thanks
