### ISSUE TITLE
Error uploading attachments via Zoo beta (webdav) two-way sync

### ISSUE THREAD

**Issue by camayl** [mickstar/Zoo-For-Zotero#97]
When I annotate a pdf and want to re-upload the file after being prompted by Zoo, I get the following error:
"Error uploading attachment
java.net.SocketTimeoutException: timeout"

Is there any way to fix this?

**Comment by camayl** [comment]
is there maybe a way of raising the timeout-time?

**Comment by mickstar** [comment]
Sure, it could be but I don't think raising the timeout will fix the error, socket timeouts occur when the server doesnt respond in a timely fashion. Theis can just occur randomly, because the server is inaccessible or because the server doesn't like the way the request is formed.

**Comment by LZeitler** [comment]
I'm getting a very similar problem, namely
`javax.net.ssl.SSLException: Write error: ssl=0x76c4cb31c8: I/O error during system call, Broken pipe`
This problem only occurs simetimes but I'm so far unable to detect a pattern. Could have do with file size? (https://stackoverflow.com/questions/8053824/ssl-broken-pipe). SO might suggest raising timeout.
I think this is an importan issue to fix as the app is pretty useless for most users (I assume) with large libraries

**Comment by camayl** [comment]
The issue resolved after I switched cloud (was using koofr before and now i switched to driveonweb).

**Comment by LZeitler** [comment]
Yes switched too. Unfortunately from 4shared to koofr. I guess I'll try
driveonweb next. Thanks for the suggestion.

camayl <notifications@github.com> schrieb am Sa., 5. Sep. 2020, 05:46:

**Comment by camayl** [comment]
Hey just a hint if you use driveonweb: once you sign in with webdav on
zotero, go back to driveonweb and have a look inside the "zotero" folder.
For some reason, for me, "_NEW" was appended to the folders in there. Once
I removed "_NEW" from both folders in there, the sync worked correctly.

**Comment by LZeitler** [comment]
> I'm getting a very similar problem, namely
> `javax.net.ssl.SSLException: Write error: ssl=0x76c4cb31c8: I/O error during system call, Broken pipe`
> This problem only occurs sometimes but I'm so far unable to detect a pattern. Could have to do with file size? (https://stackoverflow.com/questions/8053824/ssl-broken-pipe). SO might suggest raising timeout.
> I think this is an important issue to fix as the app is pretty useless for most users (I assume) with large libraries


Switching to driveonweb worked to resolve this issue.

**Comment by mickstar** [comment]
resolved in latest.
